### ISSUE TITLE
Learn Jekyll static site generator and maintain team website

### ISSUE THREAD

**Issue by CCharlieLi** [SkyroverTech/skyrovertech.github.io#1]
Hi @philip-knight 

I need your help to maintain system team website, and your duty is:
- To deloy and update Jekyll static site
- To maintain the content like: short articles, team mates info and team history.

before you can take this job, you need to:
- Install Ruby( by default you already have it on your Mac and just skip this step)
- Learn and install [Jekyll](http://jekyllrb.com/)
- Run a demo at your localhost and make sure you know each part in the project
- `Clone` skyrovertech.github.io into a new folder and try to understand the project structure
- When you finish your modification, push your code to master branch.
- Wait and refresh the [site](http://systemteam.skyrover.com.cn/), you will see changes you made.

**Comment by philip-knight** [comment]
ok

**Comment by CCharlieLi** [comment]
Hi @philip-knight 
I've pushed a demo post, please pull the latest project to your localhost. and please:
- Try to figure out how to make a post according to the demo instruction and make one.
- Try to modify `Our Amazing Team` part in `_config.yml`, put all our name in it. 
- Ask other guys for their photo, and it should be in right size 225x225.

**Comment by philip-knight** [comment]
Roger  that

**Comment by philip-knight** [comment]
HI @CCharlieLi 
昨天修改了post博文，同步之后，之前博文也没了。想问一下，你那有之前博文的格式吗，发一个我看一下。

**Comment by CCharlieLi** [comment]
@philip-knight 
I saw that the two posts are still there, I'm not sure what you mean. Anyway.

Good work! We are almost done here. Next, please:
- Investigate how to deploy the mail configuration of `Contact us`

**Comment by philip-knight** [comment]
今天老师布置了一个任务，邮箱的问题今天不能去解决，推迟到明天解决。

**Comment by philip-knight** [comment]
1：研究了一下背景图片的添加，在agence中添加了部分代码完成了PORTFOLIO和header的背景图。
2：学习了jekyl博文入门介绍以及文档格式，目前是刚开始。
问题：对team以及timelIne的背景图没有添加成功，其中team里面添加会显示在每个成员都显示一个背景图，没有解决，求告知，time。

**Comment by CCharlieLi** [comment]
@philip-knight 
1. Looks good. We may need images with proper color, also the text in header `"Welcome to SkyroverTech System Studio...."` may need to be modified and it depends on you.
2. You should learn to use markdown, as you can see that github supported markdown and we will use it everywhere in the future.
3. As what you did [here](https://github.com/SkyroverTech/skyrovertech.github.io/blob/master/_includes/css/agency.css#L359), the `#portfolio{...}` in css maps to `id="portfolio"` in [html markup](https://github.com/SkyroverTech/skyrovertech.github.io/blob/master/_includes/portfolio_grid.html#L2). So I've added [#about](https://github.com/SkyroverTech/skyrovertech.github.io/blob/master/_includes/css/agency.css#L447) and [#team](https://github.com/SkyroverTech/skyrovertech.github.io/blob/master/_includes/css/agency.css#L651) which is the mapped stylesheet of [`id="about"`](https://github.com/SkyroverTech/skyrovertech.github.io/blob/master/_includes/about.html#L2) and [`id="team"`](https://github.com/SkyroverTech/skyrovertech.github.io/blob/master/_includes/team.html#L2).
4. For the mail function, look at [here](https://github.com/SkyroverTech/skyrovertech.github.io/blob/master/js/contact_me.js), it is functioned by javascript.

**Comment by philip-knight** [comment]
1:图片id已经修改，目前先临时找了些深色图，以后可以随时替换。
2：正在学习，进展不是很快，因为最近实验室的项目压的比较紧，中间去了一趟天津做单位项目的测试，党务了5天。
3：此处搞明白了，但是，我配上深色的图，about 和团队介绍的字体是灰色，显示不清楚，晚上我找了一下， <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Portfolio</h2>
                    <h3 class="section-subheading text-muted">Our time and stories.</h3>
修改col却不成功，望指教，在其中试了一下文字的位置，成功了。
4：邮件系统网页没有响应成功，我再看看其实现的大概逻辑。

**Comment by CCharlieLi** [comment]
Done, thanks. Closing.
